import type { Car } from '@/types/car';

export const cars: Car[] = [
  {
    brand: 'Porsche',
    model: '911 Turbo S',
    img: '/popular1.webp',
    acceleration: '2,7',
    topSpeed: '330',
    fuelGas: '66.6',
    price: '373,000',
  },
  {
    brand: 'Porsche',
    model: '911 Carrera 4 GTS',
    img: '/popular2.webp',
    acceleration: '3,0',
    topSpeed: '312',
    fuelGas: '66.6',
    price: '265,700',
  },
  {
    brand: 'Porsche',
    model: 'Panamera Turbo S E-Hybrid',
    img: '/popular3.webp',
    acceleration: '2,9',
    topSpeed: '325',
    fuelGas: '79.8',
    price: '265,700',
  },
  {
    brand: 'Porsche',
    model: 'Cayenne Turbo GT',
    img: '/popular4.webp',
    acceleration: '3,3',
    topSpeed: '305',
    fuelGas: '89.7',
    price: '303,700',
  },
  {
    brand: 'Porsche',
    model: '911 GT3',
    img: '/popular5.webp',
    acceleration: '3,4',
    topSpeed: '318',
    fuelGas: '64',
    price: '300,400',
  },
  {
    brand: 'Porsche',
    model: 'Taycan GTS',
    img: '/popular6.webp',
    acceleration: '3,3',
    topSpeed: '250',
    fuelGas: 'Electric',
    price: '207,700',
  },
];
